# Generated by Django 3.2.6 on 2021-09-05 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('S_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
